"""add summary fields

Revision ID: 464d55d82d0e
Revises: 50e54a7b8d80
Create Date: 2026-06-08 18:20:13.563553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464d55d82d0e'
down_revision: Union[str, Sequence[str], None] = '50e54a7b8d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('key_points', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'key_points')
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
